### ISSUE TITLE
Launch shouldn't implement Module

### ISSUE THREAD

**Issue by ODAKAB** [kaiserdj/Plugin-Launcher-Darkbot#1]
This supposed to be identified as a Task, using Module makes it look like a module in module list.

**Comment by kaiserdj** [comment]
I did not understand what you mean, sorry

**Comment by ODAKAB** [comment]
![image](https://user-images.githubusercontent.com/49538323/105752377-4556a880-5f58-11eb-96b8-80ef75d4c4c6.png)
I can modify and send a pull request if you are okay with it.

**Comment by kaiserdj** [comment]
Thank you, and I'm sorry for not having done it before, I've been very busy these days 😅
