### ISSUE TITLE
Useragent disappears after 2 tabs

### ISSUE THREAD

**Issue by ghost** [kaiserdj/Plugin-Launcher-Darkbot#3]
Steps to reproduce:

Go to skylab > disable or enable any module ( a new tab will be opened ) > Start the game from the new tab

If you cause the launcher to open another tab in any way, the third tab will not get the useragent.

**Comment by kaiserdj** [comment]
Thanks for telling me the bug, I have already fixed it. For the next version that will come out soon, it will be solved

**Comment by kaiserdj** [comment]
For next time, please post the issues at https://github.com/kaiserdj/Darkorbit-client/issues
